version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r app/requirements.txt
    build:
      commands:
        - echo "Running unit tests..."
        - pytest app/
    post_build:
      commandss:
        - echo "Tests completed successfully!"

