version: 0.2

phases:
  install:
    commands:
      - echo "Downloading official Terraform binary..."
      # Added -f (fail silently on server errors) and -L (follow redirects)
      - curl -f -L -s -q https://releases.hashicorp.com/terraform/1.15.0/terraform_1.15.0_linux_amd64.zip -o /tmp/terraform.zip

      - echo "Extracting binary..."
      - unzip -o -q /tmp/terraform.zip -d /tmp/

      - echo "Granting execution permission to terraform binary..."
      - chmod +x /tmp/terraform

      - echo "Moving terraform binary to /usr/local/bin..."
      - mv /tmp/terraform /usr/local/bin/

      - echo "Verifying installation..."
      - terraform --version

  build:
    commands:
      - echo "Synchronizing infrastructure state..."
      - echo "bucket = \"$BACKEND_BUCKET_NAME\"" > terraform/backend-config.tfvars

      - cd terraform
      - terraform init -input=false -backend-config=backend-config.tfvars
      - terraform apply -auto-approve
